stateDiagram-v2

    [*] --> Pending

    Pending --> SearchingRiders

    SearchingRiders --> RiderAssigned

    SearchingRiders --> Cancelled

    RiderAssigned --> ClientConfirmed

    RiderAssigned --> RiderRejected

    RiderRejected --> SearchingRiders

    ClientConfirmed --> InDelivery

    InDelivery --> Delivered

    InDelivery --> Cancelled